package board.util;

public enum QueryKeys {
	MEMBER_SELECT_ONE("MEMBER-SELECT-ONE"),
	MEMBER_INSERT("MEMBER-INSERT"),
	MEMBER_GET_COUNT("MEMBER-GET-COUNT"),
	MEMBER_UPDATE("MEMBER-UPDATE"),
	BBS_INSERT("BBS-INSERT"),
	BBS_IMG_INSERT("BBS-IMG-INSERT"),
	BBS_UPDATE("BBS-UPDATE"),
	BBS_IMG_UPDATE("BBS-IMG-UPDATE"),
	BBS_TAGS_UPDATE("BBS-TAGS-UPDATE"),
	BBS_IMG_SELECT("BBS-IMG-SELECT"),
	BBS_DELETE("BBS-DELETE"),
	BBS_IMG_DELETE("BBS-IMG-DELETE"),
	BBS_SELECT("BBS-SELECT"),
	BBS_SELECT_ALL("BBS-SELECT-ALL"),
	BBS_SELECT_ALL_FIRST("BBS-SELECT-ALL-FIRST"),
	BBS_TOTAL_COUNT("BBS-TOTAL-COUNT"),
	LIKES_SELECT("LIKES-SELECT"),
	LIKES_DELETE("LIKES-DELETE"),
	LIKES_INSERT("LIKES-INSERT"),
	BBS_SELECT_ALL_USER("BBS-SELECT-ALL-USER"),
	TOKEN_INSERT("TOKEN-INSERT"),
	TOKEN_DELETE("TOKEN-DELETE"),
	TOKEN_SELECT("TOKEN-SELECT"),
	LIKES_DELETE_ALL("LIKES-DELETE-ALL");
	String key;
	
	QueryKeys(String key) {
		this.key=key;
	}
	
	public String getValue() {
		return key;
	}

}
